[package]
name = "algebrix"
version = "0.1.0"
edition = "2024"

[lib]
name = "algebrix"
path = "src/lib.rs"

[dependencies]
glam = {version="0.31.0", optional = true}
nalgebra = {version="0.34.1", optional = true}

[features]
default = ["std", "simd"]
std = []
simd = []  # Auto-detect SIMD
simd-x86 = []  # Force x86_64 SIMD
simd-arm = []  # Force ARM SIMD
scalar-math = []  # Disable SIMD, use scalar only
glam-compatibility = ["dep:glam"]
nalgebra-compatibility = ["dep:nalgebra"]
